# Generated by Django 2.1.2 on 2018-10-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'superuser'), (1, 'teacher'), (2, 'accountant'), (3, 'librarian'), (4, 'student')], null=True),
        ),
    ]
