# Generated by Django 2.1.2 on 2018-10-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181015_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='account.Subject'),
        ),
    ]
