# Generated by Django 2.1.2 on 2018-10-16 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_student_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='account_type',
        ),
    ]
