# Generated by Django 2.1.2 on 2018-10-19 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20181016_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registered_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
