# Generated by Django 2.1.2 on 2018-10-26 21:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeTable',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.Student')),
                ('credit', models.PositiveIntegerField(default=0)),
                ('dues', models.PositiveIntegerField(default=0)),
                ('paid_sem', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='registered_on',
        ),
        migrations.AddField(
            model_name='student',
            name='registered_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
