# Generated by Django 2.1 on 2018-11-08 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181026_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feetable',
            old_name='credit',
            new_name='paid_till_now',
        ),
        migrations.RemoveField(
            model_name='feetable',
            name='dues',
        ),
        migrations.RemoveField(
            model_name='feetable',
            name='paid_sem',
        ),
    ]
