# Generated by Django 2.1.2 on 2018-11-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181108_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='subjects',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
