# Generated by Django 2.1 on 2018-11-18 20:38

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20181118_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', django_mysql.models.ListCharField(models.PositiveIntegerField(default=0), blank=True, max_length=28, size=7)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='result',
            name='student',
        ),
        migrations.AddField(
            model_name='semester',
            name='subjects',
            field=django_mysql.models.ListCharField(models.CharField(max_length=30), blank=True, max_length=217, size=7),
        ),
    ]
