# Generated by Django 2.1 on 2018-11-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20181118_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcard',
            name='student',
        ),
        migrations.RemoveField(
            model_name='result',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='result',
            name='year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='registered_on',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True),
        ),
        migrations.DeleteModel(
            name='ReportCard',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
