# Generated by Django 2.1 on 2018-11-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20181119_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='subjects',
        ),
    ]
